name: .NET Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:

    runs-on: macos-latest

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x
          
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Restore dependencies
      run: dotnet workload install maui-maccatalyst
        
    - name: Restore dependencies
      run: dotnet restore source/MacDynamicDesktop.Mac.sln
      
    - name: Version Visual Studio SDK projects
      uses: roryprimrose/set-vs-sdk-project-version@v1.0.3
      with:
        # The wildcard filter that identifies projects to version
        projectFilter: "**/*.csproj"
        # Maps to the Version element
        version: 1.0.${{ github.run_number }}
        # Maps to the AssemblyVersion element
        assemblyVersion: 1.0.${{ github.run_number }}
        # Maps to the FileVersion element
        fileVersion: 1.0.${{ github.run_number }}
        # Maps to the InformationalVersion element
        informationalVersion: 1.0.${{ github.run_number }}
      
    - name: Build
      shell: pwsh
      run: |
        dotnet build source/MacDynamicDesktop.Mac.sln --configuration Release --no-restore
      
    - name: Publish
      shell: pwsh
      run: |
        dotnet publish source/MacDynamicDesktop.Mac.sln -f net7.0-maccatalyst -c Release -p:CreatePackage=false
        
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: 1.0.${{ github.run_number }}
        path: "**/*.app"
